In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# К признаку стажа добавим признаки: средняя стоимость занятия,
# квалификация репетитора
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450,
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 
               1, 3, 3, 1, 2]])

In [ ]:
X.T.shape

In [ ]:
y = [45, 55, 50, 59, 65,
    35, 75, 80, 50, 60]

In [ ]:
# Нормализация [0, 1]
X[2].min(), X[2].max()

In [ ]:
X_norm = X.copy()
X_norm = X_norm.astype(np.float64)
X_norm

In [ ]:
X_norm[1] = (X[1] - X[1].min()) / (X[1].max() - X[1].min())
X_norm

In [ ]:
X_norm[2] = (X[2] - X[2].min()) / (X[2].max() - X[2].min())
X_norm

In [ ]:
# Стандартизация

In [ ]:
plt.hist(X_norm[2])

In [ ]:
plt.hist(X[2])

In [ ]:
X1_mean = X[1].mean()
X1_mean

In [ ]:
X1_std = X[1].std()
X1_std

In [ ]:
X_st = X.copy().astype(np.float64)

In [ ]:
X_st[1] = (X[1] - X1_mean) / X1_std
X_st

In [ ]:
np.mean(X_st[1]), np.std(X_st[1])

In [ ]:
plt.hist(X[1])

In [ ]:
plt.hist(X_st[1])

In [ ]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [ ]:
X_st[2] = calc_std_feat(X[2])

In [ ]:
X_st[3] = calc_std_feat(X[3])
X_st

In [ ]:
X_st

In [ ]:
from sklearn.preprocessing import StandardScaler # Стандартизация
from sklearn.preprocessing import MinMaxScaler # [0, 1]

In [ ]:
# SGD

In [29]:
# выбор объекта 
idx = np.random.randint(0, X.T.shape[0])
X.T[idx]

array([  1,   1, 500,   1])

In [30]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [31]:
def eval_model(X, y, iterations, alpha=1e-4):
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= (alpha * (1/n * 2 * np.dot((y_pred - y), X.T)))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [33]:
eval_model(X_st, y, iterations=5000, alpha=1e-2)

500 [57.39774247  5.33339208  2.20519115  4.11956429] 39.89829860457438
1000 [57.39999991  5.84797255  1.75110131  4.06416803] 39.79478180199176
1500 [57.4         6.02214987  1.56124795  4.08214956] 39.7803874176269
2000 [57.4         6.0844181   1.48281933  4.09930384] 39.77817174731625
2500 [57.4         6.10764604  1.45064459  4.10866832] 39.777815666203836
3000 [57.4         6.11657814  1.43749879  4.11305506] 39.777757486291065
3500 [57.4         6.12008375  1.43214066  4.11497868] 39.77774792231456
4000 [57.4         6.12147781  1.42995986  4.1157945 ] 39.77774634666134
4500 [57.4         6.12203677  1.42907302  4.11613425] 39.77774608686836
5000 [57.4         6.12226203  1.42871255  4.11627429] 39.77774604402161


array([57.4       ,  6.12226203,  1.42871255,  4.11627429])

In [34]:
def eval_sgd_model(X, y, iterations, qty_in_batch=1, alpha=1e-4):
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    n_batch = n // qty_in_batch
    if n % qty_in_batch != 0:
        n_batch += 1
    for i in range(1, iterations+1):
        for b in range(n_batch):
            start_ = qty_in_batch*b
            end_ = qty_in_batch*(b+1)

            # print(b, n_batch, start_, end_)

            X_tmp = X[:, start_ : end_]
            y_tmp = y[start_ : end_]
            y_pred_tmp = np.dot(W, X_tmp)
            err = calc_mse(y_tmp, y_pred_tmp)
            W -= (alpha * (1/n * 2 * np.dot((y_pred_tmp - y_tmp), X_tmp.T)))

    if i % (iterations / 10) == 0:
        print(i, W, err)
    return W

In [ ]:
%whos

In [35]:
X.T.shape

# batch_size = 2
# 0-2, 2-4, ..., 8-10 - 5 групп
# 1 эпоха

(10, 4)

In [36]:
eval_sgd_model(X_st, y, iterations=5000, qty_in_batch=1, alpha=1e-2)

5000 [57.38844578  6.08411105  1.41620295  4.14060863] 5.095062934375206


array([57.38844578,  6.08411105,  1.41620295,  4.14060863])

In [ ]:
# early_stopping
# задаем очень большое число эпозх -> 1e5
# n = 25, 50, 100, 

# 1000
# 200
# ...
# 0.01

In [37]:
from sklearn.linear_model import LinearRegression, SGDClassifier, SGDRegressor
from sklearn.linear_model import Lasso, Ridge

In [ ]:
Lasso().fit(X.T, y)

In [ ]:
Ridge().fit(X.T, y)

In [ ]:
# L1 регуляризация - Lasso

f(x, W) + (lambda_/2) * np.sum(np.abs(W))

In [ ]:
# L2 регуляризация - Ridge

f(x, W) + (lambda_/2) * np.sum(W**2)

df/dw1 = d(w1**2 + w2**2 + w3**2) / dw1 = 2*w1 + 0 + 0 = 2*w1

In [ ]:
f'(x, W) + lambda_ * np.sum(W)

In [ ]:
def eval_model_reg2(X, y, iterations, alpha=1e-4, lambda_=1e-8):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * W) 
    if i % (iterations / 10) == 0:
        print(i, W, err)
    return W

In [ ]:
eval_model_reg2(X_st, y, iterations=5000, alpha=1e-2, lambda_=1e-4)

In [ ]:
# В некоторых алгоритмах используется обратный коэффициент
C = 1/lambda

In [ ]:
X.T

In [ ]:
y

In [ ]:
# X -> X_train, X_valid
# 70/30, 80/20
# Кросс-валидация


# R2 = 0.75
# Доверительный интервал: [0.65, 0.85], [0.74, 0.76] 95%

In [ ]:
# X - конечная выборка
# Генеральная совокупность

# Пример: средняя зарплата в России
# Эксперимент 1: X
# Эксперименте 2: 1.1*x
# Эксперименте 3: 0.98*x

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error

In [ ]:
y_true = [0, 1, 1, 0, 1]
y_pred = [10, 5, 2, 1, 0]

mean_squared_error(y_true, y_pred)

In [ ]:
r2_score(y_true, y_pred)

In [ ]:
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold