## Урок 1. Домашнее задание

### Задание 1
Подберите скорость обучения($\alpha$) и количество итераций:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
y = np.array([45, 55, 50, 59, 65, 35, 75, 80, 50, 60])

X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
X.shape

(2, 10)

In [3]:
def calc_mse(y, y_pred):
    return np.mean((y - y_pred) ** 2)

In [4]:
# Изменим размерность X
X = np.swapaxes(X, 0, 1)
X.shape

(10, 2)

In [5]:
n = X.shape[0]
alpha = 1e-02
gamma = 0.1
step_lr = 1000
eps = 1e-06

W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [6]:
for i in range(1, 2000):
    y_pred = X @ W
    err_prev = calc_mse(y, y_pred)
    W_prev = W.copy()

    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X.T[ii] * (y_pred - y)))

    if i % 100 == 0:
        print(i, W, err_prev, alpha)

    # Scheduler step
    if i % step_lr == 0:
        alpha *= gamma

    if np.linalg.norm(W_prev - W) < eps:
        print(f'Stop: {i} iteration')
        break

100 [31.72648327  6.77395294] 177.92494760058077 0.01
200 [41.78014899  4.91746666] 62.255347042578386 0.01
300 [45.3151501   4.26470166] 47.95490496498401 0.01
400 [46.55810299  4.0351809 ] 46.18691542730009 0.01
500 [46.99514157  3.95447839] 45.968335680716045 0.01
600 [47.14881009  3.92610232] 45.94131227101915 0.01
700 [47.20284196  3.91612492] 45.93797131796627 0.01
800 [47.22184028  3.91261674] 45.93755826989325 0.01
900 [47.22852033  3.91138321] 45.93750720401236 0.01
1000 [47.23086913  3.91094949] 45.93750089064509 0.01
1100 [47.23099498  3.91092625] 45.937500709853005 0.001
1200 [47.23110839  3.91090531] 45.93750057651057 0.001
Stop: 1288 iteration


In [7]:
# Аналитическое решение:
W_0 = np.linalg.inv(X.T @ X) @ X.T @ y
W_0

array([47.23214286,  3.91071429])

Решение полученное аналитически и решение полученное методом градиентного спуска совпадают с точностью до 2-3 знака после запятой

**2\*. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:**

In [8]:
n = X.shape[0]
alpha = 1e-02
gamma = 0.1
step_lr = 1000
eps = 1e-06

W_old = W.copy()
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [9]:
for i in range(1, 2000):
    y_pred = X @ W
    err_prev = calc_mse(y, y_pred)
    W_prev = W.copy()

    # for ii in range(W.shape[0]):
    # W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
    W -= (alpha * (1 / n * 2 * X.T @ (y_pred - y)))

    if i % 100 == 0:
        print(i, W, err_prev, alpha)

    # Scheduler step
    if i % step_lr == 0:
        alpha *= gamma

    if np.linalg.norm(W_prev - W) < eps:
        print(f'Stop: {i} iteration')
        break

100 [31.72648327  6.77395294] 177.92494760058085 0.01
200 [41.78014899  4.91746666] 62.25534704257841 0.01
300 [45.3151501   4.26470166] 47.95490496498401 0.01
400 [46.55810299  4.0351809 ] 46.18691542730009 0.01
500 [46.99514157  3.95447839] 45.968335680716045 0.01
600 [47.14881009  3.92610232] 45.94131227101915 0.01
700 [47.20284196  3.91612492] 45.93797131796625 0.01
800 [47.22184028  3.91261674] 45.93755826989325 0.01
900 [47.22852033  3.91138321] 45.93750720401236 0.01
1000 [47.23086913  3.91094949] 45.93750089064509 0.01
1100 [47.23099498  3.91092625] 45.93750070985302 0.001
1200 [47.23110839  3.91090531] 45.93750057651057 0.001
Stop: 1288 iteration


In [10]:
W_old == W

array([ True,  True])

Получили точно такой же результат