In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.randn((3, 4, 5))
x

tensor([[[-1.3536,  1.1928,  0.1528,  0.0943, -1.0910],
         [ 0.3455,  1.0514, -0.1953,  0.6922,  0.2697],
         [-0.8403, -1.4688, -0.2942,  1.6853,  0.7853],
         [ 0.6762, -0.1783, -1.0801, -2.4705,  0.8178]],

        [[ 0.2750,  0.8239, -1.6782,  0.8222,  0.3128],
         [ 0.1725,  0.4593,  1.1690, -2.2588,  0.2450],
         [ 0.2066,  0.4975,  0.0450, -0.8708,  0.2354],
         [-0.4933, -0.8950,  0.0473,  0.1454,  0.5774]],

        [[ 0.9027, -1.0547, -1.8679, -0.9314,  1.5602],
         [ 0.9707, -0.9653,  0.9568, -0.1543,  0.0956],
         [ 0.4284,  0.1092, -0.0851,  0.1726,  0.4152],
         [-0.4871,  0.5585,  0.0656, -0.9481, -0.7805]]])

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x = x.reshape(6, 10)
x

tensor([[-1.3536,  1.1928,  0.1528,  0.0943, -1.0910,  0.3455,  1.0514, -0.1953,
          0.6922,  0.2697],
        [-0.8403, -1.4688, -0.2942,  1.6853,  0.7853,  0.6762, -0.1783, -1.0801,
         -2.4705,  0.8178],
        [ 0.2750,  0.8239, -1.6782,  0.8222,  0.3128,  0.1725,  0.4593,  1.1690,
         -2.2588,  0.2450],
        [ 0.2066,  0.4975,  0.0450, -0.8708,  0.2354, -0.4933, -0.8950,  0.0473,
          0.1454,  0.5774],
        [ 0.9027, -1.0547, -1.8679, -0.9314,  1.5602,  0.9707, -0.9653,  0.9568,
         -0.1543,  0.0956],
        [ 0.4284,  0.1092, -0.0851,  0.1726,  0.4152, -0.4871,  0.5585,  0.0656,
         -0.9481, -0.7805]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y = torch.Tensor([1, 4, 2, 2, 1])
res = (x.reshape(-1, 1) * y.reshape(1, -1)).reshape(6, 10, 5)
res

tensor([[[-1.3536, -5.4142, -2.7071, -2.7071, -1.3536],
         [ 1.1928,  4.7710,  2.3855,  2.3855,  1.1928],
         [ 0.1528,  0.6111,  0.3055,  0.3055,  0.1528],
         [ 0.0943,  0.3773,  0.1886,  0.1886,  0.0943],
         [-1.0910, -4.3642, -2.1821, -2.1821, -1.0910],
         [ 0.3455,  1.3819,  0.6910,  0.6910,  0.3455],
         [ 1.0514,  4.2057,  2.1029,  2.1029,  1.0514],
         [-0.1953, -0.7810, -0.3905, -0.3905, -0.1953],
         [ 0.6922,  2.7689,  1.3845,  1.3845,  0.6922],
         [ 0.2697,  1.0786,  0.5393,  0.5393,  0.2697]],

        [[-0.8403, -3.3613, -1.6807, -1.6807, -0.8403],
         [-1.4688, -5.8751, -2.9376, -2.9376, -1.4688],
         [-0.2942, -1.1769, -0.5885, -0.5885, -0.2942],
         [ 1.6853,  6.7411,  3.3706,  3.3706,  1.6853],
         [ 0.7853,  3.1410,  1.5705,  1.5705,  0.7853],
         [ 0.6762,  2.7050,  1.3525,  1.3525,  0.6762],
         [-0.1783, -0.7134, -0.3567, -0.3567, -0.1783],
         [-1.0801, -4.3205, -2.1603, -2.1603, 

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
(x @ x.T).shape

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad=True)
z = Variable(torch.Tensor([0.5]), requires_grad=True)
t = Variable(torch.Tensor([2]), requires_grad=True)

y = x ** 3 + z - 75 * t

y.backward()

print(f"Значение производной в заданной точке:\n\
        ({float(x.grad)}, {float(z.grad)}, {float(t.grad)})")

Значение производной в заданной точке:
        (3.0, 1.0, -75.0)


In [8]:
# Создайте единичный тензор размера 5x6
x = torch.ones((5, 6))
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [9]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [10]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте

In [11]:
from torch import nn 
from torch import optim

In [12]:
w1 = Variable(torch.randn(1), requires_grad=True)
x = Variable(torch.Tensor([2]), requires_grad=False)
y = Variable(torch.Tensor([4]), requires_grad=False)

def func(x, w1):
    return x ** w1 - 2 * x ** 2 + 5

print(y, x, w1)

tensor([4.]) tensor([2.]) tensor([0.4151], requires_grad=True)


In [13]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [14]:
for epoch in range(201):
    optimizer.zero_grad()
    pred = func(x, w1)
    loss = criterion(pred, y)
    if epoch % 25 == 0:
        print(f"epoch {epoch}: loss {float(loss)}")
    loss.backward()
    optimizer.step()

epoch 0: loss 32.1102180480957
epoch 25: loss 28.94913673400879
epoch 50: loss 24.723487854003906
epoch 75: loss 19.127552032470703
epoch 100: loss 12.246849060058594
epoch 125: loss 5.506824970245361
epoch 150: loss 1.441318154335022
epoch 175: loss 0.2189614623785019
epoch 200: loss 0.023955492302775383


In [15]:
print(y, x, w1)

tensor([4.]) tensor([2.]) tensor([2.7766], requires_grad=True)
