In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.randn((3, 4, 5))
x

tensor([[[-3.6528e-01, -4.5810e-01,  4.3816e-01,  7.8949e-01, -6.1171e-01],
         [-2.2505e+00,  7.5638e-01, -1.0191e-01, -1.4775e+00,  1.8637e-01],
         [ 8.0090e-01,  2.1542e-01,  1.9270e+00,  2.7989e-01,  1.1451e-01],
         [-1.6297e+00,  3.8300e-02,  1.1131e+00,  7.7536e-01, -1.2007e+00]],

        [[-2.0097e+00,  5.3053e-01, -1.4673e+00,  1.4006e+00, -1.6787e+00],
         [-3.5861e-04, -4.1250e-01,  5.8672e-01,  9.7122e-01, -9.8870e-01],
         [-9.2050e-01,  4.3236e-01, -4.8875e-01,  9.1294e-01,  3.5948e-01],
         [-1.4846e+00,  1.3668e+00,  8.1092e-01,  1.2287e-01,  3.1357e+00]],

        [[ 1.3075e+00, -5.3380e-01, -5.3660e-01, -1.6881e+00,  1.0682e+00],
         [ 9.8679e-01, -5.6559e-01,  2.6263e+00, -2.3833e-01,  1.2843e+00],
         [ 9.7912e-02, -6.1176e-01,  7.9929e-01,  1.2438e+00,  1.3008e+00],
         [ 3.5526e-01, -9.0061e-01, -9.7461e-01,  3.3702e-01,  1.1757e-01]]])

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x = x.reshape(6, 10)
x

tensor([[-3.6528e-01, -4.5810e-01,  4.3816e-01,  7.8949e-01, -6.1171e-01,
         -2.2505e+00,  7.5638e-01, -1.0191e-01, -1.4775e+00,  1.8637e-01],
        [ 8.0090e-01,  2.1542e-01,  1.9270e+00,  2.7989e-01,  1.1451e-01,
         -1.6297e+00,  3.8300e-02,  1.1131e+00,  7.7536e-01, -1.2007e+00],
        [-2.0097e+00,  5.3053e-01, -1.4673e+00,  1.4006e+00, -1.6787e+00,
         -3.5861e-04, -4.1250e-01,  5.8672e-01,  9.7122e-01, -9.8870e-01],
        [-9.2050e-01,  4.3236e-01, -4.8875e-01,  9.1294e-01,  3.5948e-01,
         -1.4846e+00,  1.3668e+00,  8.1092e-01,  1.2287e-01,  3.1357e+00],
        [ 1.3075e+00, -5.3380e-01, -5.3660e-01, -1.6881e+00,  1.0682e+00,
          9.8679e-01, -5.6559e-01,  2.6263e+00, -2.3833e-01,  1.2843e+00],
        [ 9.7912e-02, -6.1176e-01,  7.9929e-01,  1.2438e+00,  1.3008e+00,
          3.5526e-01, -9.0061e-01, -9.7461e-01,  3.3702e-01,  1.1757e-01]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y = torch.Tensor([1, 4, 2, 2, 1])
res = (x.reshape(-1, 1) * y.reshape(1, -1)).reshape(6, 10, 5)
res

tensor([[[-3.6528e-01, -1.4611e+00, -7.3056e-01, -7.3056e-01, -3.6528e-01],
         [-4.5810e-01, -1.8324e+00, -9.1621e-01, -9.1621e-01, -4.5810e-01],
         [ 4.3816e-01,  1.7527e+00,  8.7633e-01,  8.7633e-01,  4.3816e-01],
         [ 7.8949e-01,  3.1580e+00,  1.5790e+00,  1.5790e+00,  7.8949e-01],
         [-6.1171e-01, -2.4469e+00, -1.2234e+00, -1.2234e+00, -6.1171e-01],
         [-2.2505e+00, -9.0021e+00, -4.5011e+00, -4.5011e+00, -2.2505e+00],
         [ 7.5638e-01,  3.0255e+00,  1.5128e+00,  1.5128e+00,  7.5638e-01],
         [-1.0191e-01, -4.0765e-01, -2.0382e-01, -2.0382e-01, -1.0191e-01],
         [-1.4775e+00, -5.9099e+00, -2.9550e+00, -2.9550e+00, -1.4775e+00],
         [ 1.8637e-01,  7.4547e-01,  3.7274e-01,  3.7274e-01,  1.8637e-01]],

        [[ 8.0090e-01,  3.2036e+00,  1.6018e+00,  1.6018e+00,  8.0090e-01],
         [ 2.1542e-01,  8.6169e-01,  4.3084e-01,  4.3084e-01,  2.1542e-01],
         [ 1.9270e+00,  7.7082e+00,  3.8541e+00,  3.8541e+00,  1.9270e+00],
         [

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
(x @ x.T).shape

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad=True)
z = Variable(torch.Tensor([0.5]), requires_grad=True)
t = Variable(torch.Tensor([2]), requires_grad=True)

y = x ** 3 + z - 75 * t

y.backward()

print(f"Значение производной в заданной точке:\n\
        ({float(x.grad)}, {float(z.grad)}, {float(t.grad)})")

Значение производной в заданной точке:
        (3.0, 1.0, -75.0)


In [8]:
# Создайте единичный тензор размера 5x6
x = torch.ones((5, 6))
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
# Переведите его в формат numpy
x = x.numpy()
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [12]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте

In [13]:
from torch import nn 
from torch import optim

In [14]:
w1 = Variable(torch.randn(1), requires_grad=True)
x = Variable(torch.Tensor([2]), requires_grad=False)
y = Variable(torch.Tensor([4]), requires_grad=False)

def func(x, w1):
    return x ** w1 - 2 * x ** 2 + 5

print(y, x, w1)

tensor([4.]) tensor([2.]) tensor([0.7297], requires_grad=True)


In [15]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [16]:
for epoch in range(201):
    optimizer.zero_grad()
    pred = func(x, w1)
    loss = criterion(pred, y)
    if epoch % 25 == 0:
        print(f"epoch {epoch}: loss {float(loss)}")
    loss.backward()
    optimizer.step()

epoch 0: loss 28.534229278564453
epoch 25: loss 24.168203353881836
epoch 50: loss 18.40909194946289
epoch 75: loss 11.43833065032959
epoch 100: loss 4.87977409362793
epoch 125: loss 1.1952482461929321
epoch 150: loss 0.17284689843654633
epoch 175: loss 0.018487872555851936
epoch 200: loss 0.0017550238408148289


In [17]:
print(y, x, w1)

tensor([4.]) tensor([2.]) tensor([2.7991], requires_grad=True)
