In [15]:
import torch

In [16]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.randn((3, 4, 5))
x

tensor([[[ 0.3706, -0.0164, -0.1865,  1.0748, -0.0736],
         [ 1.0247, -0.1131, -1.1834, -0.2037, -0.6935],
         [-0.2501, -1.7376,  0.1323, -1.3774,  1.4115],
         [-0.3661,  0.5385, -1.1685,  0.4695, -0.9749]],

        [[ 1.0536, -0.5228, -0.1516, -1.0032,  0.4486],
         [ 0.0036,  1.0406, -1.6038,  0.4744, -1.0056],
         [ 0.8568,  0.5661,  0.5385,  1.0945,  1.3227],
         [-0.4694,  1.6012,  0.1695, -0.8541,  0.8204]],

        [[-0.1069, -1.1291,  0.6809,  1.5536, -0.1595],
         [-0.3820, -0.9476, -0.9808,  0.0640, -0.4597],
         [-0.6883, -0.9081,  0.2110,  0.7788,  0.3134],
         [-0.3095,  2.2428, -0.6173, -0.3510, -1.8574]]])

In [17]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [18]:
# Приведите его к форме 6 X 10
x = x.reshape(6, 10)
x

tensor([[ 0.3706, -0.0164, -0.1865,  1.0748, -0.0736,  1.0247, -0.1131, -1.1834,
         -0.2037, -0.6935],
        [-0.2501, -1.7376,  0.1323, -1.3774,  1.4115, -0.3661,  0.5385, -1.1685,
          0.4695, -0.9749],
        [ 1.0536, -0.5228, -0.1516, -1.0032,  0.4486,  0.0036,  1.0406, -1.6038,
          0.4744, -1.0056],
        [ 0.8568,  0.5661,  0.5385,  1.0945,  1.3227, -0.4694,  1.6012,  0.1695,
         -0.8541,  0.8204],
        [-0.1069, -1.1291,  0.6809,  1.5536, -0.1595, -0.3820, -0.9476, -0.9808,
          0.0640, -0.4597],
        [-0.6883, -0.9081,  0.2110,  0.7788,  0.3134, -0.3095,  2.2428, -0.6173,
         -0.3510, -1.8574]])

In [19]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y = torch.Tensor([1, 4, 2, 2, 1])
res = (x.reshape(-1, 1) * y.reshape(1, -1)).reshape(6, 10, 5)
res

tensor([[[ 3.7064e-01,  1.4826e+00,  7.4129e-01,  7.4129e-01,  3.7064e-01],
         [-1.6360e-02, -6.5440e-02, -3.2720e-02, -3.2720e-02, -1.6360e-02],
         [-1.8648e-01, -7.4593e-01, -3.7296e-01, -3.7296e-01, -1.8648e-01],
         [ 1.0748e+00,  4.2990e+00,  2.1495e+00,  2.1495e+00,  1.0748e+00],
         [-7.3568e-02, -2.9427e-01, -1.4714e-01, -1.4714e-01, -7.3568e-02],
         [ 1.0247e+00,  4.0990e+00,  2.0495e+00,  2.0495e+00,  1.0247e+00],
         [-1.1314e-01, -4.5254e-01, -2.2627e-01, -2.2627e-01, -1.1314e-01],
         [-1.1834e+00, -4.7338e+00, -2.3669e+00, -2.3669e+00, -1.1834e+00],
         [-2.0369e-01, -8.1475e-01, -4.0737e-01, -4.0737e-01, -2.0369e-01],
         [-6.9351e-01, -2.7740e+00, -1.3870e+00, -1.3870e+00, -6.9351e-01]],

        [[-2.5015e-01, -1.0006e+00, -5.0030e-01, -5.0030e-01, -2.5015e-01],
         [-1.7376e+00, -6.9503e+00, -3.4752e+00, -3.4752e+00, -1.7376e+00],
         [ 1.3227e-01,  5.2906e-01,  2.6453e-01,  2.6453e-01,  1.3227e-01],
         [

In [20]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
(x @ x.T).shape

torch.Size([6, 6])

In [21]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad=True)
z = Variable(torch.Tensor([0.5]), requires_grad=True)
t = Variable(torch.Tensor([2]), requires_grad=True)

y = x ** 3 + z - 75 * t

y.backward()

print(f"Значение производной в заданной точке:\n\
        ({float(x.grad)}, {float(z.grad)}, {float(t.grad)})")

Значение производной в заданной точке:
        (3.0, 1.0, -75.0)


In [22]:
# Создайте единичный тензор размера 5x6
x = torch.ones((5, 6))
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [23]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [24]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте

In [25]:
from torch import nn 
from torch import optim

In [26]:
w1 = Variable(torch.randn(1), requires_grad=True)
x = Variable(torch.Tensor([2]), requires_grad=False)
y = Variable(torch.Tensor([4]), requires_grad=False)

def func(x, w1):
    return x ** w1 - 2 * x ** 2 + 5

print(y, x, w1)

tensor([4.]) tensor([2.]) tensor([-0.0274], requires_grad=True)


In [27]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [28]:
for epoch in range(201):
    optimizer.zero_grad()
    pred = func(x, w1)
    loss = criterion(pred, y)
    if epoch % 25 == 0:
        print(f"epoch {epoch}: loss {float(loss)}")
    loss.backward()
    optimizer.step()

epoch 0: loss 36.22624969482422
epoch 25: loss 34.3332633972168
epoch 50: loss 31.882774353027344
epoch 75: loss 28.646493911743164
epoch 100: loss 24.318403244018555
epoch 125: loss 18.602863311767578
epoch 150: loss 11.654321670532227
epoch 175: loss 5.043615818023682
epoch 200: loss 1.2574553489685059


In [29]:
print(y, x, w1)

tensor([4.]) tensor([2.]) tensor([2.5646], requires_grad=True)
